### PR TITLE
add defaults directory for sshd

### PR DESCRIPTION
**Pull request by shibumi**
When using variables make sure to initialize them.
Otherwise the CI will run in an error for the tests.

### CODE REVIEW

**Comment by jelly** [comment]
Nack from me, this isn't really obvious and might disable our firewall.

**Comment by shibumi** [comment]
The other way around would be enabling a firewall on default.. but having no default variables at all is bad Ansible practice.  Variables should be always at least defined

**Comment by grazzolini** [comment]
> The other way around would be enabling a firewall on default.. but having no default variables at all is bad Ansible practice. Variables should be always at least defined

Yes, we have that issue with the vault variables too, they are not defined if you don't have access to the vault. @jelly this place is the least precedence of all of ansible. Anywhere else we change this to true will cause the firewall to be working. I think that we can make it true by default and disable it instead on a book if needed. @shibumi can you change it to true?

**Comment by shibumi** [comment]
grazzolini sure I can change this to true, but let's wait for jelles approval. I might need to change it to false then on the hosts where it shouldn't get installed.

**Comment by grazzolini** [comment]
Honestly I don't see any place where it shouldn't have the firewall enabled. But sure. I have added @jelly to the reviewers, to make it formalized.

**Comment by jelly** [comment]
So, I find it confusing to define "global" variables also locally in a role. I haven't looked at how this test solution works but maybe it can define the variables which are "missing"?

An alternative would be:
```
when: configure_firewall is defined and configure_firewall
```

**Comment by shibumi** [comment]
Your change could fix this. Shall I test it? We have tests now :D

**Comment by grazzolini** [comment]
We don't have a place for global variables either. Which sucks. I need a global var on the AUR role (or at least that is available on more than one role) but it does not work. Anyway, @shibumi can you test it and perhaps push to this branch?

**Comment by shibumi** [comment]
Sorry, I totally forgot about this PR. I have applied @jelly 's suggestion. The molecule test is fine with this solution. Are you fine with it, too?

**Comment by shibumi** [comment]
@grazzolini ready to merge?

**Comment by jelly** [comment]
Merged outside of Github

**Pull request closed without merging**
